Med_Id.web/Controllers/CourierTypeController.cs
using Med_Id.datamodels;
using Med_Id.viewmodels;
using Med_Id.web.Services;
using Microsoft.AspNetCore.Mvc;

namespace Med_Id.web.Controllers
{
    public class CourierTypeController : Controller
    {
        private CourierService courierService;
        private CourierTypeService courierTypeService;
        private int IdUser = 1;

        public CourierTypeController(CourierService _courierService, CourierTypeService _courierTypeService)
        {

            this.courierService = _courierService;
            this.courierTypeService = _courierTypeService;

        }
        public async Task<IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMCourierType> data = await courierTypeService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Name.ToLower().Contains(searchString.ToLower())
                ).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Name).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Name).ToList();
                    break;
            }
            return View(PaginationList<VMCourierType>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }
        public async Task<IActionResult> Create()
        {
            VMCourierType data = new VMCourierType();

            List<MCourier> listCourier = await courierService.GetAllData();
            ViewBag.ListCourier = listCourier;

            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create(VMCourierType dataParam)
        {
            VMResponse respon = await courierTypeService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }
        public async Task<IActionResult> Edit(int id)
        {
            VMCourierType data = await courierTypeService.GetDataById(id);

            List<MCourier> listCourier = await courierService.GetAllData();
            ViewBag.ListCourier = listCourier;

            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(VMCourierType dataParam)
        {
            VMResponse respon = await courierTypeService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMCourierType data = await courierTypeService.GetDataById(id);

            List<MCourier> listCourier = await courierService.GetAllData();
            ViewBag.ListCourier = listCourier;

            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Detail(VMCourierType dataParam)
        {
            VMResponse respon = await courierTypeService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }
        public async Task<IActionResult> Delete(int id)
        {
            VMCourierType data = await courierTypeService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> SureDelete(int id, int DeletedBy)
        {

            VMResponse respon = await courierTypeService.Delete(id, DeletedBy);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", id);
        }
    }
}

Med_Id.web/Views/CourierType/Create.cshtml
@using Med_Id.viewmodels
@model VMCourierType
@{
    //Layout = null;
    ViewData["Title"] = "Create Courier  Type";

}
<div class="card">
    <div class="card-body">
        <h2 class="text-left display-6">@ViewData["Title"]</h2>


        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-4 row a">
                <label for="Name" class="col-sm-4 col-form-label">Name*</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name">

                </div>
            </div>

            <div class="mb-4 row">
                <label for="CourierId" class="col-sm-4 col-form-label">Name Courier</label>
                <div class="col-sm-8">
                    @Html.DropDownList("CourierId",
                    new SelectList(ViewBag.ListCourier, "Id", "Name"),
                    "--Pilih Kategori--",
                    new { @class= "form-control" }
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="CourierType" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "is-invalid text-danger",
        rules: {
            Name: {
                required: true,
                minlength: 3,
            },
            CourierId: "required",
        },
        messages: {
            Name: {
                required: "Please fill name Courier!",
                minlength: "The Name must consist of at least 3 character!",
            },
            CourierId: "Plese Select Category",

        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize();


            $.ajax({
                url: "/CourierType/Create",
                type: "POST",
                dataType: "json",
                data: dataForm,
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $("#myModal").modal("hide")

                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {

                        toastr.error(data.message)
                    }
                }
            })
        }
    })
</script>

Med_Id.web/Views/CourierType/Delete.cshtml
@using Med_Id.viewmodels
@model VMCourierType

@{
    Layout = null;
    ViewData["Title"] = "Courier Delete";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />
            <h3>Are you sure for delete @Model.Name ?</h3>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-light">Back to Index</a>

            </div>
        </form>

    </div>
</div>

Med_Id.web/Views/CourierType/Detail.cshtml
@using Med_Id.viewmodels
@model VMCourierType
@{
    //Layout = null;
    ViewData["Title"] = "Edit Courier  Type";

}
<div class="card">
    <div class="card-body">
        <h2 class="text-left display-6">@ViewData["Title"]</h2>

        <form asp-action="Detail" method="post" id="form_input">
            <input type="hidden" name="Id" id="Id" value="@Model.Id" />
            <div class="mb-4 row a">
                <label for="Name" class="col-sm-4 col-form-label">Name*</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name" readonly>

                </div>
            </div>

            <div class="mb-4 row a">
                <label for="NameCourier" class="col-sm-4 col-form-label">Name*</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCourier" name="NameCourier" value="@Model.NameCourier" readonly>

                </div>
            </div>
@*
            <div class="mb-4 row">
                <label for="CourierId" class="col-sm-4 col-form-label">Name Courier</label>
                <div class="col-sm-8">
                    @Html.DropDownList("CourierId",
                    new SelectList(ViewBag.ListCourier, "Id", "Name"),
                    "--Pilih Kategori--",
                    new { @class= "form-control" }
                    )
                </div>
            </div>*@

            <div class="mb-4 row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="CourierType" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>
</div>

Med_Id.web/Views/CourierType/Edit.cshtml
@using Med_Id.viewmodels
@model VMCourierType
@{
    //Layout = null;
    ViewData["Title"] = "Edit Courier  Type";

}
<div class="card">
    <div class="card-body">
        <h2 class="text-left display-6">@ViewData["Title"]</h2>

        <form asp-action="Edit" method="post" id="form_input">
            <input type="hidden" name="Id" id="Id" value="@Model.Id" />
            <div class="mb-4 row a">
                <label for="Name" class="col-sm-4 col-form-label">Name*</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name">
                    <span id="validate_name" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="CourierId" class="col-sm-4 col-form-label">Name Courier</label>
                <div class="col-sm-8">
                    @Html.DropDownList("CourierId",
                    new SelectList(ViewBag.ListCourier, "Id", "Name"),
                    "--Pilih Kategori--",
                    new { @class= "form-control" }
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="CourierType" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "is-invalid text-danger",
        rules: {
            Name: {
                required: true,
                minlength: 3,
            },
            CourierId: "required",
        },
        messages: {
            Name: {
                required: "Please fill name Courier!",
                minlength: "The Name must consist of at least 3 character!",
            },
            CourierId: "Plese Select Category",

        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize();

            var name = $("#Name").val()

            $.ajax({
                url: "/Courier/CheckNameIsExist",
                type: "get",
                data: { name: name },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_name").text("Name Courier is Already Exists")
                        return true;
                    } else {
                        fungsiSubmit(dataForm)
                    }
                }
            })

            $.ajax({
                url: "/CourierType/Edit",
                type: "POST",
                dataType: "json",
                data: dataForm,
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $("#myModal").modal("hide")

                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {

                        toastr.error(data.message)
                    }
                }
            })
        }
    })
</script>

Med_Id.web/Views/CourierType/Index.cshtml
@using Med_Id.viewmodels
@model Med_Id.viewmodels.PaginationList<VMCourierType>

<div class="card">
    <div class="card-header">

        <div class="row mb-3">
            <div class="col-12">
                <div class="card-title">@ViewData["Title"]</div>
                <div class="d-flex justify-content-between">
                    <button type="button" id="btn_create" class="btn btn-outline-dark">
                        Create

                    </button>

                    <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
                        <div class="input-group w-100">
                            <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="Search">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default" title="search">
                                    <i class="fas fa-search"></i>
                                </button>

                                <a class="btn btn-default" asp-action="Index" title="reset">
                                    <i class="fas fa-redo"></i>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                                Name CourierType
                        </th>
                        <th>Name Courier</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count != 0)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@item.NameCourier</td>

                                <td>
                                    <button type="button" class="btn btn-outline-dark btn_edit" dataid="@item.Id">
                                        Edit
                                    </button>

                                    @*<button type="button" class="btn btn-outline-dark btn_detail" dataid="@item.Id">
                                        Detail
                                    </button>*@

                                    <button type="button" class="btn btn-outline-dark btn_delete" dataid="@item.Id">
                                        Delete
                                    </button>

                                </td>

                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="3">
                                <i>Data not found</i>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- card-body -->

        <div class="card-footer">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }
            <div class="row">
                <div class="col-2">

                    @*<form asp-action="Index" id="form_pagesize">
                        <select name="PageSize" id="PageSize"
                                class="form-control">
                            <option value="3">3</option>
                            <option value="5">5</option>
                            <option value="10">10</option>
                        </select>
                    </form>*@
                </div>
                <div class="col-10" >
                    Page @Model.PageIndex of @Model.TotalPages
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex + 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="btn btn-info float-right @nextDisabled">
                        Next
                    </a>

                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex - 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="btn btn-info float-right mr-1 @prevDisabled">
                        Previous
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $("#btn_create").click(function () {
            $("#myModal_body").empty();
            $("#myModal_body").load("/CourierType/Create")
            $("#myModal").modal("show");
        });

        $(".btn_detail").click(function () {

            var id = $(this).attr("dataid")
            $("#myModal_body").empty();
            $("#myModal_body").load("/CourierType/Detail?id=" + id)
            $("#myModal").modal("show");
        });

        $(".btn_edit").click(function () {

            var id = $(this).attr("dataid")
            $("#myModal_body").empty();
            $("#myModal_body").load("/CourierType/Edit?id=" + id)
            $("#myModal").modal("show");
        });

        $(".btn_delete").click(function () {
            var id = $(this).attr("dataid");
            $("#myModal_body").empty();
            $("#myModal_body").load("/CourierType/Delete?id=" + id)
            $("#myModal").modal("show");
        });

        $("#PageSize").val(@ViewBag.CurrentPageSize)

        $("#PageSize").change(function () {
            $("#form_pagesize").submit();
        })

    });
</script>