Med_Id.web/Controllers/CourierController.cs
using Med_Id.web.Services;
using Microsoft.AspNetCore.Mvc;
using Med_Id.datamodels;
using Med_Id.viewmodels;

namespace Med_Id.web.Controllers
{
    public class CourierController : Controller
    {
        private CourierService courierService;
        private int IdUser = 1;

        public CourierController(CourierService _courierService)
        {
            this.courierService = _courierService;

        }
        public async Task<IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<MCourier> data = await courierService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Name.ToLower().Contains(searchString.ToLower())
                ).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Name).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Name).ToList();
                    break;
            }
            return View(PaginationList<MCourier>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public IActionResult Create()
        {
            MCourier data = new MCourier();
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create(MCourier dataParam)
        {
            VMResponse respon = await courierService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
       
        public async Task<IActionResult> Edit(int id)
        {
            MCourier data = await courierService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(MCourier dataParam)
        {
            VMResponse respon = await courierService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
        public async Task<IActionResult> Delete(int id)
        {
            MCourier data = await courierService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> SureDelete(int id, int DeletedBy)
        {
            DeletedBy = IdUser;
            VMResponse respon = await courierService.Delete(id, DeletedBy);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", id);
        }
        public async Task<IActionResult> Detail(int id)
        {
            MCourier data = await courierService.GetDataById(id);
            return PartialView(data);
        }
        public async Task<JsonResult> CheckNameIsExist(string name)
        {
            bool isExist = await courierService.CheckCourierByName(name);
            return Json(isExist);
        }
    }
}

Med_Id.web/Views/Courier/Create.cshtml
@using Med_Id.datamodels
@model MCourier
@{
    //Layout = null;
    ViewData["Title"] = "Create";

}
<div class="card">
    <div class="card-body">
        <h2 class="text-left display-6">@ViewData["Title"]</h2>


        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-4 row a">
                <label for="Name" class="col-sm-4 col-form-label">Name*</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name">
                    <span id="validate_name" class="text-danger"></span>
                </div>
            </div>


            <div class="mb-4 row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Courier" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "is-invalid text-danger",
        rules: {
            Name: {
                required: true,
                minlength: 3,
            }
        },
        messages: {
            Name: {
                required: "Please fill name Courier!",
                minlength: "The Name must consist of at least 3 character!",
            }

        },
        //membuat validasi jika nama kategori sudah ada
		submitHandler: function(form) {
			var dataForm = $(form).serialize();

			var name = $("#Name").val()

			$.ajax({
				url: "/Courier/CheckNameIsExist",
				type: "GET",
				data: { name: name },
				dataType: "JSON",
				success: function(respon) {
					if (respon) {
						$("#validate_name").text("Name Courier is Already Exists")
						return true;
					} else {
						fungsiSubmit(dataForm)
					}
				}
			})
		}
	})
	function fungsiSubmit(dataParam) {
		$.ajax({
			url: "/Courier/Create",
			data: dataParam,
			method: "post",
			dataType: "json",
			success: function(respon) {
				var data = respon.dataRespon
				if (data.success) {
					$("#myModal").modal("hide")
					//toastr.success(data.message)
					//window.location.reload()
					toastr.success(
						data.message,
						'',
                        {
							timeOut : 500,
							fadeOut : 500,
                            onHidden: function() {
								window.location.reload()
							}
						}
					)
				} else {
					//Toast.fire({
					//	icon: "Failed",
					//	title: data.message
					//})
					toastr.error(data.message)
				}
			}
		})
	}
</script>

Med_Id.web/Views/Courier/Delete.cshtml
@using Med_Id.datamodels
@model MCourier

@{
    Layout = null;
    ViewData["Title"] = "Courier Delete";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />
            <h3>Are you sure for delete @Model.Name ?</h3>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-light">Back to Index</a>

            </div>
        </form>

    </div>
</div>

Med_Id.web/Views/Courier/Detail.cshtml
@using Med_Id.datamodels
@model MCourier
@{
    //Layout = null;
    ViewData["Title"] = "Edit Courier";

}
<div class="card">
    <div class="card-body">
        <h2 class="text-left display-6">@ViewData["Title"]</h2>

        <input type="hidden" name="Id" id="Id" value="@Model.Id" />

        <form asp-action="Detail" method="post" id="form_input">
            <div class="mb-4 row a">
                <label for="Name" class="col-sm-4 col-form-label">Name*</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name" readonly>

                </div>
            </div>



            <div class="mb-4 row">
                <div class="col-sm-10">
                    
                    <a class="btn btn-light" asp-controller="Courier" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>
</div>

Med_Id.web/Views/Courier/Edit.cshtml
@using Med_Id.datamodels
@model MCourier
@{
    //Layout = null;
    ViewData["Title"] = "Edit Courier";

}
<div class="card">
    <div class="card-body">
        <h2 class="text-left display-6">@ViewData["Title"]</h2>

        <form asp-action="Edit" method="post" id="form_input">

            <input type="hidden" name="Id" id="Id" value="@Model.Id" />
            <div class="mb-4 row a">
                <label for="Name" class="col-sm-4 col-form-label">Name*</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name">

                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Courier" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "is-invalid text-danger",
        rules: {
            Name: {
                required: true,
                minlength: 3,
            }
        },
        messages: {
            Name: {
                required: "Please fill name Courier!",
                minlength: "The Name must consist of at least 5 character!",
            }

        },


        submitHandler: function (form) {
            var dataForm = $(form).serialize();


            $.ajax({
                url: "/Courier/Edit",
                type: "POST",
                dataType: "json",
                data: dataForm,
                success: function (respon) {
                    console.log(respon)
                    var data = respon.dataRespon

                    if (data.success) {
                        $("#myModal").modal("hide")

                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {

                        toastr.error(data.message)
                    }
                }
            })
        }
    })
</script>

Med_Id.web/Views/Courier/Index.cshtml
﻿@using Med_Id.datamodels
@model Med_Id.viewmodels.PaginationList<MCourier>

<div class="card">
    <div class="card-header">

        <div class="row mb-3">
            <div class="col-12">
                <div class="card-title">@ViewData["Title"]</div>
                <div class="d-flex justify-content-between">
                    <button type="button" id="btn_create" class="btn btn-outline-dark">
                        Create

                    </button>
                    
                    <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
                        <div class="input-group w-100">
                            <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="Search">

                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default" title="search">
                                    <i class="fas fa-search"></i>
                                </button>

                                <a class="btn btn-default" asp-action="Index" title="reset">
                                    <i class="fas fa-redo"></i>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                            @*<a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort">
                                <i class="fas fa-sort"></i>*@
                                Name Courier
                            </a>
                        </th>
                        
                        <th class="text-right">Action</t>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count != 0)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Name</td>

                                <td class="text-right">
                                    <button type="button" class="btn btn-outline-dark btn_edit" dataid="@item.Id">
                                        Edit
                                    </button>

                                    <button type="button" class="btn btn-outline-dark btn_delete" dataid="@item.Id">
                                        Delete
                                    </button>

                                </td>

                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="3">
                                <i>Data not found</i>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- card-body -->

        <div class="card-footer">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }
            <div class="row">
                @*<div class="col-2">

                    <form asp-action="Index" id="form_pagesize">
                        <select name="PageSize" id="PageSize"
                                class="form-control">
                            <option value="3">3</option>
                            <option value="5">5</option>
                            <option value="10">10</option>
                        </select>
                    </form>
                </div>*@
                <div class="col">
                    Page @Model.PageIndex of @Model.TotalPages
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex + 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="btn btn-info float-right @nextDisabled">
                        Next
                    </a>
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex - 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="btn btn-info float-right mr-1 @prevDisabled">
                        Previous
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $("#btn_create").click(function () {
            $("#myModal_body").empty();
            $("#myModal_body").load("/Courier/Create")
            $("#myModal").modal("show");
        });

        $(".btn_detail").click(function () {

            var id = $(this).attr("dataid")
            $("#myModal_body").empty();
            $("#myModal_body").load("/Courier/Detail?id=" + id)
            $("#myModal").modal("show");
        });

        $(".btn_edit").click(function () {

            var id = $(this).attr("dataid")
            $("#myModal_body").empty();
            $("#myModal_body").load("/Courier/Edit?id=" + id)
            $("#myModal").modal("show");
        });

        $(".btn_delete").click(function () {
            var id = $(this).attr("dataid");
            $("#myModal_body").empty();
            $("#myModal_body").load("/Courier/Delete?id=" + id)
            $("#myModal").modal("show");
        });

        $("#PageSize").val(@ViewBag.CurrentPageSize)

        $("#PageSize").change(function () {
            $("#form_pagesize").submit();
        })

    });
</script>